### ISSUE TITLE
Scott note - Cart

### ISSUE THREAD

**Issue by halfempty** [spellerberg/paulineny#25]
![IMG_0480](https://user-images.githubusercontent.com/775543/60993039-48a52780-a313-11e9-8c3f-9f6d9c55a79a.jpg)

**Comment by halfempty** [comment]
@alisongibbons It's not possible to work on the cart 'cause everything is marked "sold out". Can you make it so there's something I can add to the cart?

**Comment by alisongibbons** [comment]
Just added a few fake stock!

**Comment by alisongibbons** [comment]
@halfempty See above

**Comment by halfempty** [comment]
Made some progress on this.
Want to talk more about the mobile size.
