### ISSUE TITLE
Mailing list form

### ISSUE THREAD

**Issue by halfempty** [spellerberg/paulineny#28]

**Comment by halfempty** [comment]
@alisongibbons Can y'all provide guidance on how to style this and what language to use? (Using MailChimp)

**Comment by alisongibbons** [comment]
I made a weird landing page: https://mailchi.mp/7f7e6db7bb2d/paulinenynewsletter
keep it simple? Sign up for our mailing list! and Subscribe as the button?

**Comment by halfempty** [comment]
@alisongibbons It's in but needs styling:

https://paulineny.com/pages/info

**Comment by alisongibbons** [comment]
@halfempty  Nice and simple-- I'd say if we can make the boxes solid white and the spacing better, we're good.
