### ISSUE TITLE
Size selector is broken

### ISSUE THREAD

**Issue by halfempty** [spellerberg/paulineny#37]

**Comment by halfempty** [comment]
@alisongibbons I've reverted the selector to a drop-down, and I've got our disco button working with it. I've tested it, so I'm pretty sure it's working. But it would be great if you could confirm.

I'm going to keep trying to get our preferred formatting working. I'm going to do that in a "branch", so that if I'm not successful I can easily switch back to the drop-down. 

I'll put it back to drop-down whenever I'm not working on it. So if you see anything other than the drop-down on the site, that means I'm actively working on it.

**Comment by alisongibbons** [comment]
@halfempty It looks good and works! Just a little weird second drop down box below it in white. 
<img width="390" alt="Screen Shot 2019-08-07 at 6 16 51 PM" src="https://user-images.githubusercontent.com/48930293/62661603-924b5700-b93f-11e9-862d-1249871c1508.png">

**Comment by halfempty** [comment]
@alisongibbons That's me working on it

The whole thing is really complicated. Changing the main dropdown triggers a bunch of changes, such as to the URL. It also changes the value of that 2nd drop down. And it's the value of that 2nd drop down that gets added to the cart! Seems excessive to me...!

**Comment by halfempty** [comment]
@alisongibbons It's probably done this way because there could be more than one option. Say, size and color. And the 2nd dropdown reflects every possible combo of those things. 

That's why I'm having trouble getting "sold out" info for the 1st drop down -- it's technically only one of a number of variables influencing the "sold out" status.

The point I'm at now is trying to understand how the 1st dropdown actually triggers all the changes that it does, so I can trigger those from my own widget.

**Comment by alisongibbons** [comment]
@halfempty That sounds annoying for sure! let me know if there's anything I can do (or change my mind about) to make it easier.

**Comment by halfempty** [comment]
@alisongibbons 

ok, I have the numbers listed out again. I'll leave them up for you to see. Set one of the sizes to sold-out and you will see how that is. I can't disable the option, but the "Add to cart" button does change to "Sold out" and won't let you add it. It should look like this:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/775543/62664027-89f31c00-b93f-11e9-8382-a3152bcecca8.png">

**Note:** There's one thing in the code that's interesting... apparently there's an option called `product.has_only_default_variant`, and things work differently if that's the case. I may have more flexibility in that mode. Does this ring any bells for you? Have you seen anything in the admin that may allow you to switch into this mode?

**Comment by alisongibbons** [comment]
@halfempty hmmm from the product end 12,14,16 etc are all considered variants and are the only things I can add to (or add another section of variants) or remove. I'll keep looking.
